[default]
zig-version = "0.15.2"
verbose = true

[[target]]
name = "linux-cuda"
os = "linux"
arch = "amd64"
include = ["C:\\cuda\\include"]
packages = [
  "gocnn-lib/cublas@v11.6.1.51/demo.zip"
  # "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cudart/linux-x86_64/cuda_cudart-linux-x86_64-12.9.79-archive.tar.xz",
  # "https://developer.download.nvidia.com/compute/cuda/redist/libcublas/linux-x86_64/libcublas-linux-x86_64-12.9.1.4-archive.tar.xz"
]
link = ["cudart", "cublas"]
prefix = "./gemm"
flags = ["-tags=cuda"]

[[target]]
name = "windows-cuda"
os = "windows"
arch = "amd64"
packages = [
  # "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cudart/windows-x86_64/cuda_cudart-windows-x86_64-12.9.79-archive.zip",
  # "https://developer.download.nvidia.com/compute/cuda/redist/libcublas/windows-x86_64/libcublas-windows-x86_64-12.9.1.4-archive.zip",
]
link = ["cudart", "cublas"]
prefix = "./gemm-win"
flags = ["-tags=cuda"]
