[default]
zig-version = "master"
link = ["cudart", "cublas"]
flags = ["-tags=cuda"]
strip = true
verbose = false

[[target]]
name = "gemm"
os = "linux"
arch = "amd64"
packages = [
  "gocnn-lib/cudart@v12.9.79/linux-amd64.tar.xz",
  "https://developer.download.nvidia.com/compute/cuda/redist/libcublas/linux-x86_64/libcublas-linux-x86_64-12.9.1.4-archive.tar.xz"
]
prefix = "./gemm"

[[target]]
name = "gemm-win"
os = "windows"
arch = "amd64"
packages = [
  "gocnn-lib/cudart@v12.9.79/windows-amd64.zip",
  "https://developer.download.nvidia.com/compute/cuda/redist/libcublas/windows-x86_64/libcublas-windows-x86_64-12.9.1.4-archive.zip",
]
prefix = "./gemm-win"
