[default]
zig-version = "0.15.2"
verbose = false
link = ["cudart", "cublas"]
flags = ["-tags=cuda"]

[[target]]
name = "linux-cuda"
os = "linux"
arch = "amd64"
include = ["C:\\cuda\\include"]
packages = [
  "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cudart/linux-x86_64/cuda_cudart-linux-x86_64-12.9.79-archive.tar.xz",
  "https://developer.download.nvidia.com/compute/cuda/redist/libcublas/linux-x86_64/libcublas-linux-x86_64-12.9.1.4-archive.tar.xz"
]
prefix = "./gemm"

[[target]]
name = "windows-cuda"
os = "windows"
arch = "amd64"
packages = [
  "gocnn-lib/cudart@v12.9.79/windows-amd64.zip",
  "https://developer.download.nvidia.com/compute/cuda/redist/libcublas/windows-x86_64/libcublas-windows-x86_64-12.9.1.4-archive.zip",
]
prefix = "./gemm-win"
